baseURL = "https://tiberiusferreira.github.io/blog/"
languageCode = "en-us"
title = "TiberiusBlog"
theme = "beautifulhugo"
publishDir = "docs"
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
