baseURL = "http://example.org/"
languageCode = "en-us"
title = "TiberiusBlog"
theme = "beautifulhugo"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
